---
version: "2.0"

services:
  app:
    image: dimokus88/universe:0.0.2

    
    env:
#1.Раздел часной информации, неделитесь даннмы из этого раздела!
     - "my_root_password=" # пароль root для подключения по ssh
     - "MONIKER=" # имя ноды
     - "MNEMONIC=" # seed фраза от тестового кошелька с defund
     - "LINK_KEY=" # link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets. ссылка на размещенный pirv-validator_key.json (прямое скачивание). Подойдет и от других тестнетов на базе Cosmos.
#==================================================================
#2.Раздел переменных для работы ноды
     - "binary=seid"
     - "vers=1.0.6beta-val-count-fix"
     - "genesis=https://raw.githubusercontent.com/sei-protocol/testnet/main/sei-incentivized-testnet/genesis.json"
     - "folder=.sei"
     - "denom=usei"
     - "chain=atlantic-1"
     - "gitrep=https://github.com/sei-protocol/sei-chain.git"
     - "gitfold=sei-chain"
     #- "addrbook=https://raw.githubusercontent.com/sei-protocol/testnet/main/sei-incentivized-testnet/addrbook.json"
     - "link_rpc=https://raw.githubusercontent.com/Dimokus88/Sei/main/state_sync"
     - "SHIFT=2000"
     - "SNAP_RPC=sei.stake-take.com:36657"
     - "link_peer=https://raw.githubusercontent.com/Dimokus88/Sei/main/PEER"
#====================================   
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
      
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 3Gi
        storage:
          size: 40Gi

         
  placement:
    akash: 
      attributes:
        host: akash
      signedBy:
        anyOf:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
