---
version: "2.0"

services:
  app:
    image: dimokus88/sei:0.0.4

    
    env:
     - "my_root_password=" # пароль root для подключения по ssh
     - "MONIKER=" # имя ноды
     - "MNEMONIC=" # seed фраза от кошелька sei
     #- "LINK_KEY=" # ссылка на размещенный pirv-validator_key.json (прямое скачивание).
     - "LINK_ADDRBOOK=https://raw.githubusercontent.com/sei-protocol/testnet/master/sei-testnet-2/addrbook.json"
     #- "SNAP_RPC="
     
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
        
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          size: 150Gi
        
        
  placement:
    akash: 
      attributes:
        host: akash
      signedBy:
        anyOf:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
