---
version: "2.0"

services:
  app:
    image: dimokus88/sei:0.1.3

    
    env:
     - "my_root_password=" # пароль root для подключения по ssh
     - "MONIKER=" # имя ноды
     - "MNEMONIC=" # seed фраза от тестового кошелька с defund
     #- "LINK_KEY=" # ссылка на размещенный pirv-validator_key.json (прямое скачивание).
     #- "SNAP_RPC="
     - "vers=1.0.4beta"
     - "genesis=https://raw.githubusercontent.com/sei-protocol/testnet/master/sei-testnet-2/genesis.json"
     - "addrbook=https://raw.githubusercontent.com/sei-protocol/testnet/main/sei-testnet-2/addrbook.json"
     - "PEER=c951b5be19b4406e95a50abed0f1886ed38ed28a@89.163.164.207:26656"
     
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
        
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          size: 150Gi
        
        
  placement:
    akash: 
      attributes:
        host: akash
      signedBy:
        anyOf:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
